CREATE DATABASE project_helena;

USE project_helena;

CREATE TABLE USERS (
  ID INT PRIMARY KEY,
  SCHOOL_ID INT,
  FIRST_NAME TEXT,
  LAST_NAME TEXT,
  DEPARTMENT TEXT
);

CREATE TABLE POLICIES (
  ID INT PRIMARY KEY,
  CHECKOUT_POLICY TEXT,
  RESERVATION_POLICY TEXT,
  DEPARTMENT_POLICY TEXT
);

CREATE TABLE EQUIPMENT (
  ID INT PRIMARY KEY,
  NAME TEXT,
  DESCRIPTION TEXT,
  AVAILABLE BOOLEAN,
  CHECKED_OUT_BY INT,
  CHECKED_OUT_DATE DATE,
  DUE_DATE DATE
);
